// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using DemoA.Models;

namespace DemoA.Migrations
{
    [DbContext(typeof(StatsContext))]
    partial class StatsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("Stats.Models.Stat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<Guid?>("StatTypeId");

                    b.Property<decimal>("Value");

                    b.HasKey("Id");

                    b.HasIndex("StatTypeId");

                    b.ToTable("Stats");
                });

            modelBuilder.Entity("Stats.Models.StatType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<int>("ValueType");

                    b.HasKey("Id");

                    b.ToTable("StatTypes");
                });

            modelBuilder.Entity("Stats.Models.Stat", b =>
                {
                    b.HasOne("Stats.Models.StatType", "StatType")
                        .WithMany("Stats")
                        .HasForeignKey("StatTypeId");
                });
#pragma warning restore 612, 618
        }
    }
}
